FROM apache/superset:latest

USER root
# Install psycopg2 system-wide, then copy to venv site-packages
RUN pip install psycopg2-binary && \
    cp -r /usr/local/lib/python3.10/site-packages/psycopg2* /app/.venv/lib/python3.10/site-packages/
USER superset
