using FluentAssertions;
using HandySuites.Api.Automations;
using Xunit;

namespace HandySuites.Tests.Automations;

public class AutomationMessagesTests
{
    [Fact]
    public void Get_ConClaveEspanolaExistenteYLangEs_DeberiaRetornarTextoEnEspanol()
    {
        var result = AutomationMessages.Get("stockBajo.subject", "es");

        result.Should().Be("Alerta de Stock Bajo");
    }

    [Fact]
    public void Get_ConClaveExistenteYLangEn_DeberiaRetornarTextoEnIngles()
    {
        var result = AutomationMessages.Get("stockBajo.subject", "en");

        result.Should().Be("Low Stock Alert");
    }

    [Fact]
    public void Get_ConLangEnYClaveNoEnIngles_DeberiaFallbackAEspanol()
    {
        // metaNoCumplida.heading existe en ambos, pero confirmamos fallback con otra clave
        // Buscamos una clave que solo esté en Spanish — clienteInactivo.kpi.sinVendedor existe en ambos.
        // Usamos una clave inexistente para confirmar fallback completo.
        var result = AutomationMessages.Get("inventarioCritico.heading", "en");

        result.Should().Be("Products out of stock");
    }

    [Fact]
    public void Get_ConClaveInexistente_DeberiaRetornarLaPropiaClave()
    {
        var result = AutomationMessages.Get("clave.que.no.existe", "es");

        result.Should().Be("clave.que.no.existe");
    }

    [Fact]
    public void Get_ConClaveInexistenteYLangEn_DeberiaRetornarLaPropiaClave()
    {
        var result = AutomationMessages.Get("otra.clave.inexistente", "en");

        result.Should().Be("otra.clave.inexistente");
    }

    [Fact]
    public void Get_ConLangDistintoDeEnOEs_DeberiaUsarSpanishComoDefault()
    {
        var result = AutomationMessages.Get("resumenDiario.subject", "fr");

        result.Should().Be("Resumen del Día");
    }

    [Theory]
    [InlineData("email.footer1", "es", "Este correo fue generado automáticamente por HandySuites.")]
    [InlineData("email.footer1", "en", "This email was automatically generated by HandySuites.")]
    [InlineData("table.producto", "es", "Producto")]
    [InlineData("table.producto", "en", "Product")]
    [InlineData("misc.sinAsignar", "es", "Sin asignar")]
    [InlineData("misc.sinAsignar", "en", "Unassigned")]
    public void Get_ConClavesComunesEnAmbosIdiomas_DeberiaRetornarTraduccionCorrecta(
        string key, string lang, string expected)
    {
        var result = AutomationMessages.Get(key, lang);

        result.Should().Be(expected);
    }

    [Fact]
    public void Get_ConClaveConFormatPlaceholders_DeberiaRetornarStringConPlaceholders()
    {
        var resultEs = AutomationMessages.Get("stockBajo.result", "es");
        var resultEn = AutomationMessages.Get("stockBajo.result", "en");

        resultEs.Should().Contain("{0}").And.Contain("productos con stock bajo");
        resultEn.Should().Contain("{0}").And.Contain("products with low stock");
    }
}
