/**
 * Single source of truth for role-based permissions.
 * Used by Sidebar (navigation filtering) and usePermissions hook (programmatic checks).
 */
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: [
    'view_dashboard',
    'view_clients',
    'view_products',
    'view_discounts',
    'view_promotions',
    'view_inventory',
    'view_routes',
    'view_zones',
    'view_visits',
    'view_orders',
    'view_deliveries',
    'view_users',
    'manage_roles',
    'manage_global_settings',
    'manage_tenants',
    'manage_all_users',
    'view_all_data',
    'manage_catalogs',
    'manage_devices',
    'view_activity_logs',
    'view_automations',
  ],
  ADMIN: [
    'view_dashboard',
    'view_clients',
    'view_products',
    'view_discounts',
    'view_promotions',
    'view_inventory',
    'view_routes',
    'view_zones',
    'view_visits',
    'view_orders',
    'view_deliveries',
    'view_users',
    'view_settings',
    'view_company_settings',
    'manage_catalogs',
    'manage_devices',
    'view_activity_logs',
    'view_automations',
    'view_metas',
  ],
  SUPERVISOR: [
    'view_dashboard',
    'view_clients',
    'view_products',
    'view_orders',
    'view_deliveries',
    'view_routes',
    'view_zones',
    'view_visits',
    'view_team',
    'view_reports',
    'view_metas',
  ],
  VENDEDOR: [
    'view_dashboard',
    'view_clients',
    'view_products',
    'view_orders',
    'view_deliveries',
    'view_routes',
    'view_visits',
  ],
  VIEWER: [
    'view_dashboard',
    'view_clients',
    'view_products',
    'view_orders',
    'view_routes',
  ],
};
