CREATE TABLE IF NOT EXISTS `notification_preferences` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `UserId` int NOT NULL,
    `EmailNotifications` tinyint(1) NOT NULL DEFAULT '1',
    `PushNotifications` tinyint(1) NOT NULL DEFAULT '1',
    `SmsNotifications` tinyint(1) NOT NULL DEFAULT '0',
    `DesktopNotifications` tinyint(1) NOT NULL DEFAULT '1',
    `EmailOrderUpdates` tinyint(1) NOT NULL DEFAULT '1',
    `EmailInventoryAlerts` tinyint(1) NOT NULL DEFAULT '1',
    `EmailWeeklyReports` tinyint(1) NOT NULL DEFAULT '1',
    `PushOrderUpdates` tinyint(1) NOT NULL DEFAULT '1',
    `PushInventoryAlerts` tinyint(1) NOT NULL DEFAULT '1',
    `PushRouteReminders` tinyint(1) NOT NULL DEFAULT '1',
    `QuietHoursStart` time NULL,
    `QuietHoursEnd` time NULL,
    `TenantId` int NOT NULL,
    `activo` tinyint(1) NOT NULL DEFAULT '1',
    `creado_en` datetime(6) NOT NULL DEFAULT (UTC_TIMESTAMP(6)),
    `actualizado_en` datetime(6) NULL,
    `creado_por` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
    `actualizado_por` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
    PRIMARY KEY (`Id`),
    UNIQUE KEY `IX_notification_preferences_TenantId_UserId` (`TenantId`,`UserId`),
    KEY `IX_notification_preferences_UserId` (`UserId`),
    CONSTRAINT `FK_notification_preferences_Tenants_TenantId` FOREIGN KEY (`TenantId`) REFERENCES `Tenants` (`Id`) ON DELETE CASCADE,
    CONSTRAINT `FK_notification_preferences_Usuarios_UserId` FOREIGN KEY (`UserId`) REFERENCES `Usuarios` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;